-- A single table to hold relevant airport data
CREATE TABLE airports (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  city TEXT,
  country_code VARCHAR(2),
  country_name TEXT, -- Added country name
  iata_code VARCHAR(3) UNIQUE,
  latitude DECIMAL(11, 8),
  longitude DECIMAL(11, 8),
  type VARCHAR(20),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for fast direct lookups
CREATE INDEX idx_airports_name ON airports (name);
CREATE INDEX idx_airports_city ON airports (city);
CREATE INDEX idx_airports_iata ON airports (iata_code);

-- Enable the trigram extension for fuzzy text searching
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- A powerful index for autocomplete that searches name, city, and country
CREATE INDEX idx_airports_name_city_country_trgm ON airports
USING GIN ((name || ' ' || city || ' ' || country_name) gin_trgm_ops);
